### ISSUE TITLE
OneDrive Explorer GUI is dropping ode.settings on desktop

### ISSUE THREAD

**Issue by mark-hallman** [Beercow/OneDriveExplorer#11]
I have a desktop shortcut for OneDrive Explorer GUI.  When I launch the app by clicking on the desktop shortcut,  the file `ode.settings` is created on the desktop. Is there a way to disable this.  Would it be better to create that settings file in the folder where OneDrive Explorer GUI is installed?

**Comment by Beercow** [comment]
I did a quick test. Can you check the shortcut and see if the Start in points back to the directory that ode is in? With it empty, the settings file was created where I had the shortcut.
![image](https://user-images.githubusercontent.com/10360919/220753979-678f64b7-6969-40b6-b705-5f8ef8410476.png)

**Comment by mark-hallman** [comment]
Brian,  that was it.  I added the install path to the `start in` field and the `ode.settings` gets written to that folder.  THANKS!

**Comment by Beercow** [comment]
Any time. 😊
