### ISSUE TITLE
Feature request: Clear button for keyword searches

### ISSUE THREAD

**Issue by chadtilbury** [Beercow/OneDriveExplorer#12]
Clearing the results of a "Find" operation are a bit awkward, requiring a second "empty" search.  It would be nice to have a "Clear" button that would clear any search results.

**Comment by Beercow** [comment]
This should be fixed in the latest release.
https://github.com/Beercow/OneDriveExplorer/releases/tag/v2023.03.06

**Comment by Beercow** [comment]
Closing. New release should solve any issues.
https://github.com/Beercow/OneDriveExplorer/releases/tag/v2023.03.10
