### ISSUE TITLE
One Drive update removes user.dat file

### ISSUE THREAD

**Issue by cristianbuse** [Beercow/OneDriveExplorer#14]
Hi,

In the latest insider release of OneDrive, the dat file have been completely removed by Microsoft. The ini file is still found under ```C:\Users\<userName>\AppData\Local\Microsoft\OneDrive\settings\Business1```.

![image](https://github.com/Beercow/OneDriveExplorer/assets/23198997/3c0f0cef-4654-463a-b4ff-8fd7cfeb617c)

**Comment by Beercow** [comment]
OneDriveExplorer can use the SQLite files in place of the dat.

**Comment by cristianbuse** [comment]
Thanks for the quick reply. Just wanted to let you know of the issue just in case you did not know. Cheers

**Comment by Beercow** [comment]
Thank you. One step ahead already. There are some interesting details in the SQLite DBs I plan to add. Time permitting.
