### ISSUE TITLE
X button in Preferences window doesn't work

### ISSUE THREAD

**Issue by AndrewRathbun** [Beercow/OneDriveExplorer#15]
Love the tool, great work on it. However, this X button, which is a critical cog to the OneDriveExplorer machine, doesn't currently work!
 
![OneDriveExplorer_GUI_AVBbYTWnz9](https://github.com/Beercow/OneDriveExplorer/assets/36825567/84f9bd4e-1e10-4890-aed6-132e01284da9)

**Comment by Beercow** [comment]
That was intentional in some of the windows. I can enable them, if you wish.

**Comment by AndrewRathbun** [comment]
> That was intentional in some of the windows. I can enable them, if you wish. 

Ah good to know. I wondered if it was an oversight. No worries!

**Comment by Beercow** [comment]
The thought was, I didn’t want someone to enable/disable something then x out thinking it would be saved. This forces either clicking the save or cancel button.
