### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by hodf-cye** [Beercow/OneDriveExplorer#16]
Hey,
What are the diffrences between loading <userCid>.dat or SQLite DB?
Would appricate a reference..

**Comment by Beercow** [comment]
There was/is a traditional period where OneDrive migrated over to SQLite databases from the.dat file. SQLite databases hold more information. Depending on the version, there may be only .dat, SQLite, or both. Hope this clarifies.

**Comment by hodf-cye** [comment]
Thank you, I had an assumption that could be a version differences.
For some reason even though I'm using the newset version \<UserCid\>.dat is not present.

Could be related - I was deleting 2 files, one I was removing from RecycleBin. For some reason only the one that I've reomved from RecycleBin is shown in the GUI output. I can open an issue if you prefer.

**Comment by Beercow** [comment]
Ok. So you’re working with a version that has transitioned over to SQLite only (no .dat). You can open another issue if you wish. The missing file might be in a table that  OneDriveExplorer is not parsing yet (working on an update for this). If you are comfortable with working with SQLite files in something like DB Browser for SQLite, I can point you to the table it might be in.

**Comment by hodf-cye** [comment]
Yes please

**Comment by hodf-cye** [comment]
Reagrding the version, surprisingly the same version on my PC contains both. For some reason I assumed the .dat is updating too.

**Comment by Beercow** [comment]
Inside the SafeDelete.db, in the settings personal/buisness folder, there is a table called filter_delete_info. There might be information on your missing deleted file in there. 

From what I have seen if the .dat and the databases are present, they both should update. But like I said earlier, there is a lot more information in the databases than the .dat file has.

**Comment by hodf-cye** [comment]
The file is actually missing there too.
Could be that it realted to the fact that I was removing it with shift+delete (no RB..).
Interesting :)

Of course the file can be found in the logs.
