### ISSUE TITLE
yncEngineDatabase.db. encoding with 'base64' codec failed 

### ISSUE THREAD

**Issue by AndreVanM** [Beercow/OneDriveExplorer#17]
When I try to load the SQL-option (I do not have the .dat file), I get the following error:
Unable to parse C:\Users\XXX\AppData\Local\Microsoft\OneDrive\settings\Business1\SyncEngineDatabase.db. encoding with 'base64' codec failed (TypeError: expected bytes-like object, not NoneType)

Any help?

**Comment by Beercow** [comment]
I have a fix for that. Might not be til Monday before I get it out being the weekend. I’ll let you know when it’s fixed.

**Comment by AndreVanM** [comment]
That is great! So fast.

**Comment by Beercow** [comment]
Sorry, ran into another issue. Let me know if this is fixed in the latest release. v2024.05.17

**Comment by AndreVanM** [comment]
Thanks. It is working. Great job!
