### ISSUE TITLE
ValueError: not enough values to unpack (expected 4, got 2)

### ISSUE THREAD

**Issue by AndreVanM** [Beercow/OneDriveExplorer#18]
When I run OneNoteExplorer and load a .dat file, I get the following error:

ValueError: not enough values to unpack (expected 4, got 2)

I also tried the command line version, same issue:

Traceback (most recent call last):
  File "c:\Tools\OneDriveExplorer-2024.05.17\OneDriveExplorer\OneDriveExplorer.py", line 361, in <module>
    main()
  File "c:\Tools\OneDriveExplorer-2024.05.17\OneDriveExplorer\OneDriveExplorer.py", line 235, in main
    df, rbin_df, df_scope, scopeID = DATParser.parse_dat(args.file, account)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 4, got 2)

Please advice.

**Comment by Beercow** [comment]
I’ll take a peak. Do you happen to know which version of OneDrive? Also, do you know if it worked in the previous version of OneDriveExplorer?

**Comment by AndreVanM** [comment]
This is OneDrive personal. Based on the Stack case from the Sans For500 class. I mounted the E01 using Arsenal Image mounter. And I am not running it in a VM. I do not know if it worked in a previous versions.

**Comment by Beercow** [comment]
Sounds good. I believe I have a copy of the data.

**Comment by Beercow** [comment]
Handling error now. If you were trying to load a3936c317ac1474e_screenshot.dat, it will not parse. It is not a OneDrive settings file.

**Comment by AndreVanM** [comment]
Got you. Sorry for bothering you.
