### ISSUE TITLE
OneDriveExplorer Exits with Error using -d option

### ISSUE THREAD

**Issue by dsplice** [Beercow/OneDriveExplorer#9]
Executing command (outside of KAPE) "C:\Utils\KAPE\Modules\bin>OneDriveExplorer.exe -d E:\D\Users\Stack --csv C:\Mod\FileKnowledge" generates an error and the program exits.

     _____                ___                           ___                 _
    (  _  )              (  _`\        _               (  _`\              (_ )
    | ( ) |  ___     __  | | ) | _ __ (_) _   _    __  | (_(_)       _ _    | |    _    _ __   __   _ __
    | | | |/' _ `\ /'__`\| | | )( '__)| |( ) ( ) /'__`\|  _)_ (`\/')( '_`\  | |  /'_`\ ( '__)/'__`\( '__)
    | (_) || ( ) |(  ___/| |_) || |   | || \_/ |(  ___/| (_( ) >  < | (_) ) | | ( (_) )| |  (  ___/| |
    (_____)(_) (_)`\____)(____/'(_)   (_)`\___/'`\____)(____/'(_/\_)| ,__/'(___)`\___/'(_)  `\____)(_) v2022.05.18
                                                                    | |        by @bmmaloney97
                                                                    (_)

Parsing Stack OneDrive

Traceback (most recent call last):
  File "OneDriveExplorer.py", line 448, in <module>
  File "OneDriveExplorer.py", line 443, in main
  File "OneDriveExplorer.py", line 278, in parse_onedrive
  File "pandas\core\generic.py", line 5575, in __getattr__
AttributeError: 'DataFrame' object has no attribute 'ParentId'
[3648] Failed to execute script 'OneDriveExplorer' due to unhandled exception!

I have tried the previous versions (all the ones where -d option is available) and all give the same error.

**Comment by Beercow** [comment]
-d is mainly meant to be used with KAPE. Looks like you are after one user so -f would be best. -d scans from the root directory. If you want to use it, your command should be:

> C:\Utils\KAPE\Modules\bin>OneDriveExplorer.exe -d E:\D --csv C:\Mod\FileKnowledge

**Comment by dsplice** [comment]
I tried it through KAPE originally, which is when I started running it separately to troubleshoot.  I traced the issue down to a bad <UserCid>.dat file.  The program crashes and never gets down to another user.  Not sure if there is a way to catch the error and move along to additional processing, but that would be idea if able.

**Comment by Beercow** [comment]
Not sure if you could share, but I’m curious as to what this dat file looks like. There was a change recently. Not sure if something changed again.

**Comment by Beercow** [comment]
I’ll add a fix to catch the error in the next release. Also, —debug will give you more info.

**Comment by dsplice** [comment]
Here it is with debug. 
[OneDriveError.txt](https://github.com/Beercow/OneDriveExplorer/files/8886982/OneDriveError.txt)

**Comment by Beercow** [comment]
Pushed update.
